name: darty
description: A handy collection of Dart extensions to boost your productivity..
version: 0.0.1
author: Sasha Prokhorenko <djminikin@gmail.com>
homepage: https://github.com/minikin/darty
repository: https://github.com/minikin/darty.git
issue_tracker: https://github.com/minikin/darty/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  characters: ^0.5.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
  test_coverage:
    git:
      url: https://github.com/jogboms/test-coverage.git
