name: darty
description: A new Flutter package project.
version: 0.0.1
author: Sasha Prokhorenko <djminikin@gmail.com>
homepage: https://github.com/minikin/darty

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: 1.8.0+1
  test: ^1.9.2
  test_coverage:
    git:
      url: https://github.com/jogboms/test-coverage.git
